### ISSUE TITLE
Support of referenced schema parsing

### ISSUE THREAD

**Issue by itsavinash** [researchgate/avro-php#4]
Hi,

I was trying to parse the Avro schema which has another external referenced schema. I got the following error:
`AvroSchemaParseException]`
`demoschema is not a schema we know about`

Does this package supports parsing of referenced schema? Any help would be appreciated.

Thanks.

**Comment by ghost** [comment]
I have the same issue.

In java, there is the concept of binding the schema definitions to the java classes.

It is recommended and normal that you split your big schema of multiple record definitions that are embedded/nested into separate avsc files.

I don't know if this API has support for loading multiple avro schema files as the schema to use for writing and consuming/validating the data.

**Comment by mdio** [comment]
We've decided to close this project in favour of [flix-tech/avro-php](https://github.com/flix-tech/avro-php) which already has PHP 8.2 support.
