### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by inri13666** [researchgate/avro-php#8]
When using PHP 8.2 got following deprecation message
```
"8192: Creation of dynamic property AvroMapSchema::$type is deprecated in ../vendor/rg/avro-php/lib/avro/schema.php line 486"
```

https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by inri13666** [comment]
https://github.com/researchgate/avro-php/pull/7
OR
https://github.com/researchgate/avro-php/pull/9

**Comment by mdio** [comment]
We've decided to close this project in favour of [flix-tech/avro-php](https://github.com/flix-tech/avro-php) which already has PHP 8.2 support.
